version: "3.7"
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  exit_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - '80:3000'
      - '443:3000'
      - '3001:3001'
    environment:
      - DEVMODE=DEVELOPMENT
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app/dev
      - /app/dev/node_modules
volumes:
  pgdata: