version: "3.7"
services:
  pgdb:
    image: postgres
    container_name: exitDB
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '4321:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  exit_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: antangle/exit_server:development
    depends_on:
      - pgdb
    ports:
      - '80:3000'
      - '443:3000'
      - '3001:3001'
    environment:
      - DEVMODE=dev
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  pgdata: