version: "3.7"
services:
  pgdb:
    image: postgres
    container_name: exitDB
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports: 
      - '4321:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  exit_server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: antangle/exit_server:production
    depends_on:
      - pgdb
    ports:
      - '80:3000'
      - '3001:3001'
    env_file:
      - .env
    environment:
      - DEVMODE=prod
    volumes:
      - /app/node_modules

  redis:
    image: redis:3
    hostname: redis
    container_name: redis
    command: --port 6379
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: always

volumes:
  pgdata:
  cache:
    driver: local