FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm install nodemon -g

RUN npm install cross-env -g

RUN npm run build

EXPOSE 3000
EXPOSE 3001

CMD ["npm", "run", "start:prod"]