version: "3.7"
services:
  pgdb:
    image: postgres:14-alpine
    container_name: ${POSTGRES_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'UTC'
      PGTZ: 'UTC'
    restart: always
    ports: 
      - '4321:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  exit_server:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    image: antangle/exit_server:production
    restart: always
    depends_on:
      - pgdb
    ports:
      - '80:3000'
      - '3001:3001'
    env_file:
      - .env  
    environment:
      - DEVMODE=prod
    volumes:
      - ./logs:/app/logs
      - ./backup:/app/backup
      - /app/node_modules

  redis:
    image: redis
    hostname: redis
    container_name: redis
    command: --port 6379
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: always

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    hostname: exit-filebeat
    environment:
      - LOGSTASH_URL=${LOGSTASH_URL}
    user: root
    command: filebeat -e -strict.perms=false
    volumes: 
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - fbdata:/usr/share/filebeat/data/
      - ./logs:/logs/host/
    restart: always

volumes:
  pgdata:
  cache:
    driver: local
  fbdata:
    driver: local